### PR TITLE
Add label noise

### PR DESCRIPTION
**Pull request by vals**
This pull request adds a tool for `label_projection` datasets that introduces label noise.

We evaluate a metric such as Accuracy on test data, but we are unsure how "true" our training labels are. By evaluating the test Accuracy when we have artificially introduce label error at different levels we can look at the metric for several levels of artificial label noise. This resulting curves show how good the method will be at generalizing in the presence of mislabeled data. If curves for multiple methods are plotted on the same graph, a method whose curve have systematically better scores is the better performer.

The introduced tool method `add_label_noise` randomly relabels a fraction of the labels specified by the `noise_prob` parameter. Only labels from the training set are randomized.

### Submission type

* [x] This submission adds a new dataset
* [ ] This submission adds a new method
* [ ] This submission adds a new metric
* [ ] This submission adds a new task
* [ ] This submission adds a new Docker image
* [ ] This submission fixes a bug (link to related issue: )
* [ ] This submission adds a new feature not listed above

### Testing

* [x] This submission was written on a forked copy of SingleCellOpenProblems
* [ ] GitHub Actions "Run Benchmark" tests are passing on this base branch of this pull request (include link to passed test: )
* [ ] If this pull request is not ready for review (including passing the "Run Benchmark" tests), I will open this PR as a draft (click on the down arrow next to the "Create Pull Request" button)

### Submission guidelines

* [x] This submission follows the guidelines in our [Contributing](../blob/master/CONTRIBUTING.md) document
* [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change

### CODE REVIEW

**Comment by vals** [comment]
Discussed on card https://github.com/orgs/singlecellopenproblems/projects/8#card-57951438

**Comment by mxposed** [comment]
This is great. Do you mind if I edit it to point branch `master` instead of `task-label-projection` ? To get rid of other commits

**Comment by mxposed** [comment]
> This is great. Do you mind if I edit it to point branch `master` instead of `task-label-projection` ? To get rid of other commits

Nevermind, sorry, will fix it another way

**Comment by mxposed** [comment]
I updated the base branch for this pull requests, but the other commits did not go away. Could you please edit the pull request and see if only your commits will remain?

**Comment by mxposed** [comment]
The tests got fixed, by unfortunately they fail with your addition: https://github.com/mxposed/SingleCellOpenProblems/runs/2232474817?check_suite_focus=true#step:14:392

This is because the `loader` decorator from [here](https://github.com/mxposed/SingleCellOpenProblems/blob/master/openproblems/data/utils.py#L37) silently adds a custom attribute (two) to anndata object, and you copy your anndata object [here](https://github.com/mxposed/SingleCellOpenProblems/pull/3/files#diff-be72c5121ec68b3ec0d892ba46a155f3a47943161cc81a194f74fae8271489ebR44)

I think probably the correct way is to change the `loader` decorator so that it would add that field into `adata.uns` dictionary.
What are your thoughts? @vals

**Comment by vals** [comment]
Hm I usually don't like modifying data in place. But I think that is the assumed structure here. I'll change it to update the labels in place.

**Pull request merged**
